spring:
  application:
    name: User-Management-System-
  datasource:
    url: jdbc:mysql://localhost:3306/User
    username: root
    password: Kunal@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9090

  