spring:
  application:
    name: User-Management-System-
    
# Database Configuration MySQL   
  datasource:
    url: jdbc:mysql://localhost:3306/User
    username: root
    password: Kunal@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
#  STMP Configuration  
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: virajprjapat854@gmail.com
    password: rnqiexqhrduofodv
    properties:
           mail.smtp.auth: true
           mail.smtp.starttls.enable: true
    
  
# TomCat PortNumber   
server:
  port: 9090
